# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_time',
            field=models.IntegerField(default=1),
        ),
    ]
